name: Terraform Apply
on:
  push: 
    branches: ["master"]
    paths: ["terraform/**"]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs: 
  apply:
    name: "Terraform Apply"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set environment variables
        id: vars
        run: |
          repo_name="${{ github.repository }}"
          short_name="${repo_name##*/}"
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "REPO_NAME=$short_name" >> $GITHUB_ENV
          echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: "Terraform Init"
        working-directory: ./terraform
        run: terraform init -backend-config="bucket=${{ env.AWS_ACCOUNT_ID }}-tf-state"

      - name: "Terraform Init"
        working-directory: ./terraform
        run: terraform fmt

      - name: "Terraform Init"
        working-directory: ./terraform
        run: terraform validate

      - name: "Terraform Plan"
        working-directory: ./terraform
        run: | 
          terraform plan \
            -var="repository_name=${{ env.REPO_NAME }}" \
            -var="lambda_function_name=${{ env.REPO_NAME }}" \
            -var="api_name=${{ env.REPO_NAME }}" \
            -out=tfplan -input=false    

      - name: Terraform Apply 
        working-directory: ./terraform
        run: | 
          terraform apply \
            -var="repository_name=${{ env.REPO_NAME }}" \
            -var="lambda_function_name=${{ env.REPO_NAME }}" \
            -var="api_name=${{ env.REPO_NAME }}" \
            --auto-approve